

name: Codecov

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: MegaLinter
        uses: oxsecurity/megalinter@v6.15.0
